"""Strategy engine - generates trading advice based on analysis and portfolio."""

from dataclasses import dataclass

from stock_trading_system.agents.analyzer import AnalysisResult
from stock_trading_system.utils import get_logger

logger = get_logger("strategy")


@dataclass
class StrategyAdvice:
    """Trading advice generated by the strategy engine."""
    ticker: str
    action: str  # "buy", "sell", "hold", "watch"
    signal: str  # raw signal from analysis
    confidence: str  # "high", "medium", "low"
    suggested_position_pct: float  # suggested % of portfolio
    entry_price_low: float | None = None
    entry_price_high: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    reasoning: str = ""
    risk_warning: str = ""


class StrategyEngine:
    """Generates trading advice by combining AI analysis with portfolio context."""

    def __init__(self, config: dict):
        self._config = config
        self._max_single_position_pct = 0.20  # Max 20% in one stock

    def generate_advice(
        self,
        analysis: AnalysisResult,
        holdings: list[dict],
        current_price: float | None = None,
    ) -> StrategyAdvice:
        """Generate trading advice based on analysis and current portfolio.

        Args:
            analysis: Result from StockAnalyzer
            holdings: Current portfolio holdings from PortfolioManager
            current_price: Current stock price (optional, from data layer)
        """
        ticker = analysis.ticker
        signal = analysis.signal.upper()

        # Check if already holding this stock
        existing = next((h for h in holdings if h["ticker"] == ticker), None)
        has_position = existing is not None

        # Determine action based on signal and position
        action, reasoning = self._determine_action(signal, has_position, existing)

        # Calculate position sizing
        total_value = sum(h.get("market_value", 0) for h in holdings) or 100_000  # default 100k
        suggested_pct = self._calculate_position_size(signal, has_position, existing, total_value)

        # Calculate price levels
        stop_loss = None
        take_profit = None
        entry_low = None
        entry_high = None

        if current_price and current_price > 0:
            if action == "buy":
                entry_low = current_price * 0.97  # 3% below current
                entry_high = current_price * 1.02  # 2% above current
                stop_loss = current_price * 0.92  # 8% stop loss
                take_profit = current_price * 1.20  # 20% take profit
            elif action == "sell":
                stop_loss = current_price * 0.95  # trailing stop

        # Assess confidence
        confidence = self._assess_confidence(analysis)

        # Build risk warning
        risk_warning = self._build_risk_warning(analysis, has_position, existing)

        return StrategyAdvice(
            ticker=ticker,
            action=action,
            signal=signal,
            confidence=confidence,
            suggested_position_pct=suggested_pct,
            entry_price_low=entry_low,
            entry_price_high=entry_high,
            stop_loss=stop_loss,
            take_profit=take_profit,
            reasoning=reasoning,
            risk_warning=risk_warning,
        )

    def _determine_action(
        self, signal: str, has_position: bool, existing: dict | None
    ) -> tuple[str, str]:
        """Determine action based on signal and existing position."""
        if signal == "BUY":
            if has_position:
                pnl_pct = existing.get("pnl_pct", 0) if existing else 0
                if pnl_pct < -10:
                    return "buy", "AI信号看多，当前持仓浮亏超过10%，可考虑补仓摊低成本"
                elif pnl_pct > 20:
                    return "hold", "AI信号看多，当前持仓已盈利20%+，建议持有观察"
                else:
                    return "buy", "AI信号看多，可考虑加仓"
            else:
                return "buy", "AI信号看多，建议建仓"

        elif signal == "SELL":
            if has_position:
                return "sell", "AI信号看空，建议减仓或清仓"
            else:
                return "watch", "AI信号看空，暂不建议买入，持续观望"

        else:  # HOLD
            if has_position:
                return "hold", "AI信号中性，建议维持当前仓位"
            else:
                return "watch", "AI信号中性，暂不建议操作，列入观察名单"

    def _calculate_position_size(
        self, signal: str, has_position: bool, existing: dict | None, total_value: float
    ) -> float:
        """Calculate suggested position size as % of portfolio."""
        if signal == "SELL":
            return 0.0

        if signal == "HOLD":
            if has_position and existing:
                return existing.get("market_value", 0) / total_value
            return 0.0

        # BUY signal
        base_pct = 0.10  # Start with 10%

        if has_position and existing:
            current_pct = existing.get("market_value", 0) / total_value
            # Don't exceed max single position
            return min(current_pct + 0.05, self._max_single_position_pct)

        return min(base_pct, self._max_single_position_pct)

    def _assess_confidence(self, analysis: AnalysisResult) -> str:
        """Assess confidence level from analysis details."""
        signal = analysis.signal.upper()

        # Check if debate and risk align with signal
        debate = analysis.investment_debate
        risk = analysis.risk_assessment

        # Simple heuristic based on available data
        if isinstance(debate, dict) and isinstance(risk, dict):
            return "medium"

        if signal in ("BUY", "SELL"):
            return "medium"
        return "low"

    def _build_risk_warning(
        self, analysis: AnalysisResult, has_position: bool, existing: dict | None
    ) -> str:
        """Build risk warning message."""
        warnings = []

        if has_position and existing:
            pnl_pct = existing.get("pnl_pct", 0)
            if pnl_pct < -15:
                warnings.append(f"当前持仓浮亏{pnl_pct:.1f}%，注意止损风险")
            weight = existing.get("market_value", 0)
            if weight > 0:
                warnings.append("注意仓位集中度风险")

        if analysis.signal.upper() == "BUY":
            warnings.append("AI分析仅供参考，不构成投资建议")

        return " | ".join(warnings) if warnings else "暂无特别风险提示"
