"""Invite code generation, validation, and redemption."""

from __future__ import annotations

import secrets
import sqlite3
from datetime import datetime
from stock_trading_system.utils.timez import now_local

from stock_trading_system.utils import get_logger

logger = get_logger("auth.invite")


class InviteCodeManager:
    """Manages invite codes for user registration."""

    def __init__(self, db_path: str):
        self._db_path = db_path

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self._db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def generate(
        self, created_by: int, expires_in_days: int | None = 7,
    ) -> str:
        """Generate a new invite code."""
        code = secrets.token_urlsafe(9)  # ~12 chars
        now = now_local().strftime("%Y-%m-%d %H:%M:%S")
        expires_at = None
        if expires_in_days:
            from datetime import timedelta
            expires_at = (now_local() + timedelta(days=expires_in_days)).strftime(
                "%Y-%m-%d %H:%M:%S"
            )

        with self._conn() as conn:
            conn.execute(
                """INSERT INTO invite_codes (code, created_by, created_at, expires_at)
                   VALUES (?, ?, ?, ?)""",
                (code, created_by, now, expires_at),
            )
        logger.info("Invite code generated by user %d (expires: %s)", created_by, expires_at)
        return code

    def validate(self, code: str) -> str | None:
        """Validate a code. Returns None if valid, error reason string if invalid."""
        with self._conn() as conn:
            row = conn.execute(
                "SELECT * FROM invite_codes WHERE code = ?", (code,)
            ).fetchone()

        if row is None:
            return "invite_invalid"
        row = dict(row)
        if row.get("revoked_at"):
            return "invite_revoked"
        if row.get("used_by") is not None:
            return "invite_used"
        if row.get("expires_at"):
            try:
                exp = datetime.strptime(row["expires_at"], "%Y-%m-%d %H:%M:%S")
                if now_local() > exp:
                    return "invite_expired"
            except ValueError:
                pass
        return None

    def redeem(self, code: str, user_id: int) -> None:
        """Mark a code as used by the given user."""
        now = now_local().strftime("%Y-%m-%d %H:%M:%S")
        with self._conn() as conn:
            conn.execute(
                "UPDATE invite_codes SET used_by = ?, used_at = ? WHERE code = ?",
                (user_id, now, code),
            )

    def revoke(self, code: str) -> bool:
        """Revoke a code. Returns True if found."""
        now = now_local().strftime("%Y-%m-%d %H:%M:%S")
        with self._conn() as conn:
            cur = conn.execute(
                "UPDATE invite_codes SET revoked_at = ? WHERE code = ? AND revoked_at IS NULL",
                (now, code),
            )
            return cur.rowcount > 0

    def list_all(self) -> list[dict]:
        """List all invite codes."""
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM invite_codes ORDER BY created_at DESC"
            ).fetchall()
            return [dict(r) for r in rows]

    def list_available(self, limit: int = 20) -> list[str]:
        """List unused, non-revoked, non-expired invite codes."""
        now = now_local().strftime("%Y-%m-%d %H:%M:%S")
        with self._conn() as conn:
            rows = conn.execute(
                """SELECT code FROM invite_codes
                   WHERE used_by IS NULL
                     AND revoked_at IS NULL
                     AND (expires_at IS NULL OR expires_at > ?)
                   ORDER BY created_at ASC
                   LIMIT ?""",
                (now, limit),
            ).fetchall()
            return [r["code"] for r in rows]
